{
  "formatVersion": "1.1",
  "component": {
    "group": "com.llfbandit.app_links",
    "module": "app_links_release",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        }
      ],
      "files": [
        {
          "name": "app_links_release-1.0.0.aar",
          "url": "app_links_release-1.0.0.aar",
          "size": 3904,
          "sha512": "08aa8e25094f98d8b0be483265f6f04afcf829ff436c89d98a7fd4ce8fe0700d976e7e059a4cb34cdfadc19cb017b752ba7209e4bf167c9c501fe6f42741f7b2",
          "sha256": "d23934fb4683b62c7566962c06c44887f4ad05648ac2842e401017744bf8476c",
          "sha1": "83522ebb5acafec355e43aaed68d79a71935e6e6",
          "md5": "a6f4f0ed6cbe7c79898a79392f3d4f90"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "app_links_release-1.0.0.aar",
          "url": "app_links_release-1.0.0.aar",
          "size": 3904,
          "sha512": "08aa8e25094f98d8b0be483265f6f04afcf829ff436c89d98a7fd4ce8fe0700d976e7e059a4cb34cdfadc19cb017b752ba7209e4bf167c9c501fe6f42741f7b2",
          "sha256": "d23934fb4683b62c7566962c06c44887f4ad05648ac2842e401017744bf8476c",
          "sha1": "83522ebb5acafec355e43aaed68d79a71935e6e6",
          "md5": "a6f4f0ed6cbe7c79898a79392f3d4f90"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app_links_release-1.0.0-sources.jar",
          "url": "app_links_release-1.0.0-sources.jar",
          "size": 2734,
          "sha512": "3c1d92d3fa90e710543fcf7fd62d519639faea1e279c26c660afb2519f95d2094e40b9fe7c86092428a8fc6f3861331ebf9be47c57a2003906c5959f2cc41d2f",
          "sha256": "22009155953ee1462b16272c2c241177f64f068a5e8cf62e49fbedf2b60973aa",
          "sha1": "61b2ffaa69c97e2ec17c50685f3a9d2078b5d356",
          "md5": "99ce0b422161598e3ac483eb81509736"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app_links_release-1.0.0-javadoc.jar",
          "url": "app_links_release-1.0.0-javadoc.jar",
          "size": 267304,
          "sha512": "e45cb9849bccf6d9bb8b8100343768e9d0a5673d3fef262c415d53f6fe011388c2a39016d98f228361e08151de718136c74af32d6d758e216616a9e4bb2c605c",
          "sha256": "5898c28957ed1c085d202a1d23052c0121bfd5a5161aca49e5cf8a63c1b51289",
          "sha1": "b37afd0a445a2db9f397570907b4f54ec553d219",
          "md5": "25a51e1faa8a0f9e28cad6c1af01a8df"
        }
      ]
    }
  ]
}
