{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1e9a811bf8e70466596bcf0ea3a8b5adb5f17f7f"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-1.0.aar",
          "url": "permission_handler_android_release-1.0.aar",
          "size": 26566,
          "sha512": "fb175e24013e01506b4076620904a6a5689f2b01dd54ef403abdd9a260473841f7b3b74b646cccda2f7d06d96845b61ec73c3653de396f95c452180cd80def65",
          "sha256": "10024726a9780aef9cce6fcf9b2b3acd3d0ad399b465f35786c46c608ec523c3",
          "sha1": "cd85e9b2b5068768add5b27bd215de9c795893a3",
          "md5": "f5426826332685c0b449f6695e3653b5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1e9a811bf8e70466596bcf0ea3a8b5adb5f17f7f"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-1.0.aar",
          "url": "permission_handler_android_release-1.0.aar",
          "size": 26566,
          "sha512": "fb175e24013e01506b4076620904a6a5689f2b01dd54ef403abdd9a260473841f7b3b74b646cccda2f7d06d96845b61ec73c3653de396f95c452180cd80def65",
          "sha256": "10024726a9780aef9cce6fcf9b2b3acd3d0ad399b465f35786c46c608ec523c3",
          "sha1": "cd85e9b2b5068768add5b27bd215de9c795893a3",
          "md5": "f5426826332685c0b449f6695e3653b5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_release-1.0-sources.jar",
          "url": "permission_handler_android_release-1.0-sources.jar",
          "size": 18177,
          "sha512": "673bc0d22579ac8c7f7a50b04d3f47d4cdb85dbc8aa15bfcb371b64223d3ee8f535385b2e67dfa1230c825ecddb11e45e1a0b74410e608691074c11623d4f06e",
          "sha256": "3301b75b44b9f004580d559b28ab51dd9205289cc88ccc668ce8179f5bf24c67",
          "sha1": "7a9e4cb073bdd84100ad45b7d2c21b036815543f",
          "md5": "6347cb73f0ecc4fc5e825d6de82fca4e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_release-1.0-javadoc.jar",
          "url": "permission_handler_android_release-1.0-javadoc.jar",
          "size": 264570,
          "sha512": "3be6887e1c3eb6f4f5cc3c29d78d6fc7e76aa119efbe66eddc845188e75d33b44b42e61299641a6859221c9d35855a1e2f60318a79a1717fc60fedcf3e4aca06",
          "sha256": "93e2c4a268e21e2976e08cb0730b11145ae6c5ed6cd62d38110b22c722a3440c",
          "sha1": "25381a46620546bf71b0cbc8dee1933cc4558d5a",
          "md5": "53a8a2bb6bbaa57d24380ae1dd3da35c"
        }
      ]
    }
  ]
}
