{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_profile",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-3.0.0.aar",
          "url": "url_launcher_android_profile-3.0.0.aar",
          "size": 23570,
          "sha512": "961a6dc4d5f54ae084d228da11838b9afbb515cca5bef12f18d33d7bbdaa4581aefd81bc836a18aa9e94c0a8baad8853069037b41215580472de7d8ee3764b4e",
          "sha256": "c9fbd3b3a98d6538077bbcb6aafe2ce3f1c4081298a6bd9a3a79c3c73f740866",
          "sha1": "58a28c4e632875f338fa184701e35c512e8cafa5",
          "md5": "d85fbbba82b0f024ac2f7d6e48ee12e5"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-3.0.0.aar",
          "url": "url_launcher_android_profile-3.0.0.aar",
          "size": 23570,
          "sha512": "961a6dc4d5f54ae084d228da11838b9afbb515cca5bef12f18d33d7bbdaa4581aefd81bc836a18aa9e94c0a8baad8853069037b41215580472de7d8ee3764b4e",
          "sha256": "c9fbd3b3a98d6538077bbcb6aafe2ce3f1c4081298a6bd9a3a79c3c73f740866",
          "sha1": "58a28c4e632875f338fa184701e35c512e8cafa5",
          "md5": "d85fbbba82b0f024ac2f7d6e48ee12e5"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_profile-3.0.0-sources.jar",
          "url": "url_launcher_android_profile-3.0.0-sources.jar",
          "size": 9313,
          "sha512": "992d095df67d1b653b20de471d38ae483e298811f5bb470cad4d7ffabf553451e168e5d3ac4a9593280f6983d74eb27dfafd8ced6d70da574dc2e5648944693c",
          "sha256": "1fe028244b497b0578b3df86209499fe63afee2bba459df71d15f0cc0f3f149c",
          "sha1": "888b3d3e9e6424ca726c49ce44266330d9a165c5",
          "md5": "1e4a34aa65b526add66b2064c8175c7e"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_profile-3.0.0-javadoc.jar",
          "url": "url_launcher_android_profile-3.0.0-javadoc.jar",
          "size": 332767,
          "sha512": "f65e0d9f298d1d7292942884754356a69cdda15c677a53213d90d41378acddb19a1bc2709ed370287418bac9aaf295484d816e90dcbab09f0d89dc15b040e242",
          "sha256": "0060b65474a433010f33545194e6e211683e30ef24db9e95178c4440331b933d",
          "sha1": "19afafbda53fba35345057c80438cb6c8c98dfc9",
          "md5": "08e3877ba7ad2faaa6190819017ae68f"
        }
      ]
    }
  ]
}
