{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_profile",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.0.aar",
          "url": "url_launcher_android_profile-1.0.0.aar",
          "size": 23462,
          "sha512": "413f878498f120e96fef0059455534f221c7a9a1270715109b5fcd8a962f1e879fe46e03f960e48c89132c2d98b5cf5fd3257a2260dbe03630d092c0179155e4",
          "sha256": "61a676dbc4c9111b16658a69858bbf1914f24e4e98f3a38d7f7c308e9c2dc3da",
          "sha1": "7f04f9577fc6456ba532f92cdcac455aba9eb58d",
          "md5": "a308669279eccd289e51c218d8f82d80"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.0.aar",
          "url": "url_launcher_android_profile-1.0.0.aar",
          "size": 23462,
          "sha512": "413f878498f120e96fef0059455534f221c7a9a1270715109b5fcd8a962f1e879fe46e03f960e48c89132c2d98b5cf5fd3257a2260dbe03630d092c0179155e4",
          "sha256": "61a676dbc4c9111b16658a69858bbf1914f24e4e98f3a38d7f7c308e9c2dc3da",
          "sha1": "7f04f9577fc6456ba532f92cdcac455aba9eb58d",
          "md5": "a308669279eccd289e51c218d8f82d80"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.0-sources.jar",
          "url": "url_launcher_android_profile-1.0.0-sources.jar",
          "size": 9177,
          "sha512": "4c4a6df942f65f36ef0ac729bc1b3e3f75eb56d45f4769b931641c56d3eaa4cc76c3141315040f9806c3f719f4c1e03f5abd61c963d163ce55541d05e370d9fd",
          "sha256": "a879caf6c2029a9f5a1fe4b25d7a8adc187263877599d83cd14875b3c9d10022",
          "sha1": "ebf67d4e72669f78a252d796187c516854911975",
          "md5": "880cfdfb17fab577f5e37b8e556f038a"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_profile-1.0.0-javadoc.jar",
          "url": "url_launcher_android_profile-1.0.0-javadoc.jar",
          "size": 332767,
          "sha512": "5efdf7acc487e71f2a62551e9e4cd9068822529f44a0561ef0ff15641c162389caf0469d3f6fd9fdecc2b2117e59799023282c32edc0f6854cf5c172d7db08f6",
          "sha256": "d9432b183662a8713f99e50a9106d5626581bcb639f269caa6278596b983dd84",
          "sha1": "aabde451e815f6e7155249e9e4c5e426f18a2ab7",
          "md5": "f45e6179c0ac72a8a55b834d72c3ead7"
        }
      ]
    }
  ]
}
