{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_android_profile",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_profile-3.0.0.aar",
          "url": "sqflite_android_profile-3.0.0.aar",
          "size": 45624,
          "sha512": "da9b35c5a85ad98767a66fe994898383bb1ba035c94ea7ecd89eac11676101fa921f4aec15ff02acd2cf8c387a550d1883a6ffa70431172f7a6d707f3e0abe22",
          "sha256": "59dcadcb32863f889f406a8b709d41a6459c3d154ad04a97e53af3c9461984e6",
          "sha1": "6ae9e110a20a012933b35513f00f3573c6db1b3e",
          "md5": "d4de34d25198165e75d7d16210c48aa0"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_profile-3.0.0.aar",
          "url": "sqflite_android_profile-3.0.0.aar",
          "size": 45624,
          "sha512": "da9b35c5a85ad98767a66fe994898383bb1ba035c94ea7ecd89eac11676101fa921f4aec15ff02acd2cf8c387a550d1883a6ffa70431172f7a6d707f3e0abe22",
          "sha256": "59dcadcb32863f889f406a8b709d41a6459c3d154ad04a97e53af3c9461984e6",
          "sha1": "6ae9e110a20a012933b35513f00f3573c6db1b3e",
          "md5": "d4de34d25198165e75d7d16210c48aa0"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_profile-3.0.0-sources.jar",
          "url": "sqflite_android_profile-3.0.0-sources.jar",
          "size": 23906,
          "sha512": "84be2e0f11f6739735214c714fcf25ca7b657afc40b3b54a0f0eff0de0f085cc926571087ab261b90cb6ed1e0be787046b45db4603790b883b119c835c22aa20",
          "sha256": "a127166bbaf1689504c6fc9e5111043a0537dc09ba3ea55a6d743da958ef125a",
          "sha1": "55f721f93f9c468c9d426bc61ff59a393e267750",
          "md5": "3f9cd042a556379914178c3426bed53c"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_profile-3.0.0-javadoc.jar",
          "url": "sqflite_android_profile-3.0.0-javadoc.jar",
          "size": 341675,
          "sha512": "5b5bb743b2a23e3558713aa438a939cb401366d043236818609aeb429db465eb6a8ebbed8e02ebfd94b58e8a0654ad92dce950d9039510b032451033767fcb43",
          "sha256": "1a727b075fc55fbd1d09bbd3524d01ddfa4dfd3dd81ace8d07f44da338b83686",
          "sha1": "902e7b498d39bf5bb92b74a951654d952a1823ea",
          "md5": "313efce12187c0a14564592ebc12ee49"
        }
      ]
    }
  ]
}
