{
  "formatVersion": "1.1",
  "component": {
    "group": "com.llfbandit.app_links",
    "module": "app_links_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1e9a811bf8e70466596bcf0ea3a8b5adb5f17f7f"
          }
        }
      ],
      "files": [
        {
          "name": "app_links_release-1.0.aar",
          "url": "app_links_release-1.0.aar",
          "size": 3904,
          "sha512": "08aa8e25094f98d8b0be483265f6f04afcf829ff436c89d98a7fd4ce8fe0700d976e7e059a4cb34cdfadc19cb017b752ba7209e4bf167c9c501fe6f42741f7b2",
          "sha256": "d23934fb4683b62c7566962c06c44887f4ad05648ac2842e401017744bf8476c",
          "sha1": "83522ebb5acafec355e43aaed68d79a71935e6e6",
          "md5": "a6f4f0ed6cbe7c79898a79392f3d4f90"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1e9a811bf8e70466596bcf0ea3a8b5adb5f17f7f"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "app_links_release-1.0.aar",
          "url": "app_links_release-1.0.aar",
          "size": 3904,
          "sha512": "08aa8e25094f98d8b0be483265f6f04afcf829ff436c89d98a7fd4ce8fe0700d976e7e059a4cb34cdfadc19cb017b752ba7209e4bf167c9c501fe6f42741f7b2",
          "sha256": "d23934fb4683b62c7566962c06c44887f4ad05648ac2842e401017744bf8476c",
          "sha1": "83522ebb5acafec355e43aaed68d79a71935e6e6",
          "md5": "a6f4f0ed6cbe7c79898a79392f3d4f90"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app_links_release-1.0-sources.jar",
          "url": "app_links_release-1.0-sources.jar",
          "size": 2734,
          "sha512": "3c1d92d3fa90e710543fcf7fd62d519639faea1e279c26c660afb2519f95d2094e40b9fe7c86092428a8fc6f3861331ebf9be47c57a2003906c5959f2cc41d2f",
          "sha256": "22009155953ee1462b16272c2c241177f64f068a5e8cf62e49fbedf2b60973aa",
          "sha1": "61b2ffaa69c97e2ec17c50685f3a9d2078b5d356",
          "md5": "99ce0b422161598e3ac483eb81509736"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app_links_release-1.0-javadoc.jar",
          "url": "app_links_release-1.0-javadoc.jar",
          "size": 267298,
          "sha512": "198f383d616a6c00e2d27e6be04ea2a3c423ad972ae5e434eb3d17019399d2ca38ef62e54e57282a660bc51cbd860f485dd3aa090ae1caff6a0a80d8c912cbd1",
          "sha256": "27f34109c6018072d5e278713617f37ee706604182d7f64afcc3f58661d45d38",
          "sha1": "c859ae568fd958cd7accccddfed6766373cc0ea2",
          "md5": "32bf77e32339e1ef285ce3c1c5c12c30"
        }
      ]
    }
  ]
}
