{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_debug",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_debug-1.0.0.aar",
          "url": "path_provider_android_debug-1.0.0.aar",
          "size": 10809,
          "sha512": "1e43aadf8743080c912faea886fb53cfa3c6e095abc22d2cb98c9843cd10b042d2b2f3cf58e9a1beffe7bf4ebe00cdf0a51e13316e52e6a26120f257f1c3c397",
          "sha256": "bf82481c1e104a28682bd741ec528f4c07123eea5cba006465ddfcbbff6101f0",
          "sha1": "13a589e605bbe8ecb479eb6dd2e5c7c5ecd542e9",
          "md5": "d26bceaf772a1a4315d809b6aeece819"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_debug-1.0.0.aar",
          "url": "path_provider_android_debug-1.0.0.aar",
          "size": 10809,
          "sha512": "1e43aadf8743080c912faea886fb53cfa3c6e095abc22d2cb98c9843cd10b042d2b2f3cf58e9a1beffe7bf4ebe00cdf0a51e13316e52e6a26120f257f1c3c397",
          "sha256": "bf82481c1e104a28682bd741ec528f4c07123eea5cba006465ddfcbbff6101f0",
          "sha1": "13a589e605bbe8ecb479eb6dd2e5c7c5ecd542e9",
          "md5": "d26bceaf772a1a4315d809b6aeece819"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_debug-1.0.0-sources.jar",
          "url": "path_provider_android_debug-1.0.0-sources.jar",
          "size": 4153,
          "sha512": "8d0620e879a6668a7dcb1b54091eac971c86c0f1013d78c2728018c501598d095e00f47e47c7742978594c39df41cb896eb9d9a91c73453f6ebec7f3e3b409c2",
          "sha256": "526f898c1240196664c940f06843d55dd7f6717365c167c476386277cca3d15c",
          "sha1": "9bc69e92e2ab37ebea4cb511e4072550fe34d36a",
          "md5": "b5f0db6ff8f305f4a799b8b39e4da48d"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_debug-1.0.0-javadoc.jar",
          "url": "path_provider_android_debug-1.0.0-javadoc.jar",
          "size": 294225,
          "sha512": "e5524c3968b35d9b28227652176bc0333503aa15edab6a1808b164fd94112a0c1cb3a35c2a6435f4415755e36c4aeb9278e1043da18230c29c3241a7acd64471",
          "sha256": "389a847a9d39b3b4931956eb4e884e3600c284d8a567f8ac7c04c0f43817e93b",
          "sha1": "93bbd86e44aca60d47f30658dc9246dc8ac9f63e",
          "md5": "dff2b5276dd31eacc98a0c38391661f8"
        }
      ]
    }
  ]
}
