{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_release",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.0.0.aar",
          "url": "url_launcher_android_release-1.0.0.aar",
          "size": 22163,
          "sha512": "358272cf08f94067ce8341582674fa6cdaccaa048eddeed0ac72ebbb9c2114a78e4beb64952a16500934a6a9583a26649830b9796ce6fbf1dc8be23e8d333c19",
          "sha256": "7a151b841b909fef73d5432a84d15c49cf6d44110c2257f7fdfdfddd751a22e9",
          "sha1": "e54aed9aacd1a6c40487dd3fd7faacbfdae49ae5",
          "md5": "012dba6cab0fcbe3b074d5506861be67"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_release-1.0.0.aar",
          "url": "url_launcher_android_release-1.0.0.aar",
          "size": 22163,
          "sha512": "358272cf08f94067ce8341582674fa6cdaccaa048eddeed0ac72ebbb9c2114a78e4beb64952a16500934a6a9583a26649830b9796ce6fbf1dc8be23e8d333c19",
          "sha256": "7a151b841b909fef73d5432a84d15c49cf6d44110c2257f7fdfdfddd751a22e9",
          "sha1": "e54aed9aacd1a6c40487dd3fd7faacbfdae49ae5",
          "md5": "012dba6cab0fcbe3b074d5506861be67"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_release-1.0.0-sources.jar",
          "url": "url_launcher_android_release-1.0.0-sources.jar",
          "size": 9162,
          "sha512": "7e3bd2e3be9159622da98e5e5b1c80e3ca1e9b4afbd3e802a034560d23d3e7151d176c6b18144d174e804ad52275dbd540146a178b4337f525033e68f1979fe2",
          "sha256": "c04d32614b84573ca248e0722a706be40c939b6db4795febe35621b9b8a1db7c",
          "sha1": "e76081802d5c3406c5685427e55d75f2dcaf9bae",
          "md5": "a18f266a4d30313b06bc5b18dd0bd4d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_release-1.0.0-javadoc.jar",
          "url": "url_launcher_android_release-1.0.0-javadoc.jar",
          "size": 332767,
          "sha512": "5efdf7acc487e71f2a62551e9e4cd9068822529f44a0561ef0ff15641c162389caf0469d3f6fd9fdecc2b2117e59799023282c32edc0f6854cf5c172d7db08f6",
          "sha256": "d9432b183662a8713f99e50a9106d5626581bcb639f269caa6278596b983dd84",
          "sha1": "aabde451e815f6e7155249e9e4c5e426f18a2ab7",
          "md5": "f45e6179c0ac72a8a55b834d72c3ead7"
        }
      ]
    }
  ]
}
