{
  "formatVersion": "1.1",
  "component": {
    "group": "com.llfbandit.app_links",
    "module": "app_links_profile",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        }
      ],
      "files": [
        {
          "name": "app_links_profile-3.0.0.aar",
          "url": "app_links_profile-3.0.0.aar",
          "size": 4080,
          "sha512": "898020b2cf2df44ce718ff08f6e6f3a584e8041e54ba61b6abf8ef503a2fdcbb04633c72cd951d05b014d13efc2699a6e925213d2d5960a32be6c8d0189dac2c",
          "sha256": "ed09920c231f4004f01ed0edfc6d262019f7b539a3c7ea1c6546bb1370b195bd",
          "sha1": "b7b1659fba677d340f6d0304501458233437ff76",
          "md5": "fe77b0a965fa4f595d4ef417f8494bb8"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "app_links_profile-3.0.0.aar",
          "url": "app_links_profile-3.0.0.aar",
          "size": 4080,
          "sha512": "898020b2cf2df44ce718ff08f6e6f3a584e8041e54ba61b6abf8ef503a2fdcbb04633c72cd951d05b014d13efc2699a6e925213d2d5960a32be6c8d0189dac2c",
          "sha256": "ed09920c231f4004f01ed0edfc6d262019f7b539a3c7ea1c6546bb1370b195bd",
          "sha1": "b7b1659fba677d340f6d0304501458233437ff76",
          "md5": "fe77b0a965fa4f595d4ef417f8494bb8"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app_links_profile-3.0.0-sources.jar",
          "url": "app_links_profile-3.0.0-sources.jar",
          "size": 2734,
          "sha512": "3c1d92d3fa90e710543fcf7fd62d519639faea1e279c26c660afb2519f95d2094e40b9fe7c86092428a8fc6f3861331ebf9be47c57a2003906c5959f2cc41d2f",
          "sha256": "22009155953ee1462b16272c2c241177f64f068a5e8cf62e49fbedf2b60973aa",
          "sha1": "61b2ffaa69c97e2ec17c50685f3a9d2078b5d356",
          "md5": "99ce0b422161598e3ac483eb81509736"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app_links_profile-3.0.0-javadoc.jar",
          "url": "app_links_profile-3.0.0-javadoc.jar",
          "size": 267305,
          "sha512": "ad1a33990c892bca3ed0641814280262e69c1df3fb252d983fbf62d2759a88d2b3ee1865df89ada06fc861b2cb75c913897d58092e45864c1c76364c3a03fe09",
          "sha256": "afe3134b956900ae9b2aa61be3642d96f3fd3cddaf385b3dc65d48bd87c5606d",
          "sha1": "701856ec14d3a168c03e7ed9501b45d684382b4c",
          "md5": "564c605f42628fcb2b59a031c5d51e97"
        }
      ]
    }
  ]
}
