{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1e9a811bf8e70466596bcf0ea3a8b5adb5f17f7f"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-1.0.aar",
          "url": "sqflite_android_release-1.0.aar",
          "size": 43605,
          "sha512": "f031f1e48b67329e55eaf0ea1c7cd9ec0e75c2779239e9a09ea2eef6f0c34d559e9b7fcd2810bd71d0a7908443d7a372a7513d6f2d5b6cb147e0f9dbf9555768",
          "sha256": "89439d1977d36fd11b813f4aa429071827518d0af8caacf2f10dc933b5791997",
          "sha1": "3fe77b0a27719f135eae791cc8dd246e02687f95",
          "md5": "23722bb3a90622af9a0efd917fd478ca"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1e9a811bf8e70466596bcf0ea3a8b5adb5f17f7f"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-1.0.aar",
          "url": "sqflite_android_release-1.0.aar",
          "size": 43605,
          "sha512": "f031f1e48b67329e55eaf0ea1c7cd9ec0e75c2779239e9a09ea2eef6f0c34d559e9b7fcd2810bd71d0a7908443d7a372a7513d6f2d5b6cb147e0f9dbf9555768",
          "sha256": "89439d1977d36fd11b813f4aa429071827518d0af8caacf2f10dc933b5791997",
          "sha1": "3fe77b0a27719f135eae791cc8dd246e02687f95",
          "md5": "23722bb3a90622af9a0efd917fd478ca"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-1.0-sources.jar",
          "url": "sqflite_android_release-1.0-sources.jar",
          "size": 23906,
          "sha512": "84be2e0f11f6739735214c714fcf25ca7b657afc40b3b54a0f0eff0de0f085cc926571087ab261b90cb6ed1e0be787046b45db4603790b883b119c835c22aa20",
          "sha256": "a127166bbaf1689504c6fc9e5111043a0537dc09ba3ea55a6d743da958ef125a",
          "sha1": "55f721f93f9c468c9d426bc61ff59a393e267750",
          "md5": "3f9cd042a556379914178c3426bed53c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-1.0-javadoc.jar",
          "url": "sqflite_android_release-1.0-javadoc.jar",
          "size": 341634,
          "sha512": "8dd8b4a3f1bfc04f653dd232b68b0d47b59ac154532bdcf693cfcead41ff7d5a68ea6c5f4d1f3fce314c47541cbc13c95e1ef5c3bd3156f1cc49b0b2e20938c0",
          "sha256": "577feff6d6ab98689f0c788d05ca55df67ef7b3e0328baa9747cd3d9633e3e41",
          "sha1": "0e0be68127ec673a38ec735818c0fb7f698a7e9d",
          "md5": "5f65e45af1a55bbd6100792cef06951e"
        }
      ]
    }
  ]
}
