{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.steenbakker.mobile_scanner",
    "module": "mobile_scanner_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1e9a811bf8e70466596bcf0ea3a8b5adb5f17f7f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile_scanner_release-1.0.aar",
          "url": "mobile_scanner_release-1.0.aar",
          "size": 78741,
          "sha512": "36e1a667dfe2c72b6708dc4ec957025f99cbf38fba0abd63d54aac00eba2eaaf1af8bc8b3278568cdbeff992b338aee79d589b7ef4a68022b6166c4190f7bd64",
          "sha256": "7e1a0a081d37be1293e78cee781846d71737b72bfb865159c533022d34e62aa8",
          "sha1": "2510ee3730ef2b4b11e80d643a8e0b75379ca3fe",
          "md5": "4808a07e74cf5ab2d3bd94bb44103024"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1e9a811bf8e70466596bcf0ea3a8b5adb5f17f7f"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile_scanner_release-1.0.aar",
          "url": "mobile_scanner_release-1.0.aar",
          "size": 78741,
          "sha512": "36e1a667dfe2c72b6708dc4ec957025f99cbf38fba0abd63d54aac00eba2eaaf1af8bc8b3278568cdbeff992b338aee79d589b7ef4a68022b6166c4190f7bd64",
          "sha256": "7e1a0a081d37be1293e78cee781846d71737b72bfb865159c533022d34e62aa8",
          "sha1": "2510ee3730ef2b4b11e80d643a8e0b75379ca3fe",
          "md5": "4808a07e74cf5ab2d3bd94bb44103024"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mobile_scanner_release-1.0-sources.jar",
          "url": "mobile_scanner_release-1.0-sources.jar",
          "size": 24074,
          "sha512": "25c4ad54cfcccb2183fc365ea3330ecf708b36691061841bf62e2914be4ef9e5d5c5f5827a57c6052949ba72e8e2e5e3132406a2673dd40e28b8901c35688f6c",
          "sha256": "d5fea13d7766c2452e9bbb9425d90930732a0a55df10fa949bde4e53b1e017ee",
          "sha1": "242d0d02ffb841abc2db142e5ab97f7a209debcd",
          "md5": "bb0bb4f980749cbce4a05f5a42cab434"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mobile_scanner_release-1.0-javadoc.jar",
          "url": "mobile_scanner_release-1.0-javadoc.jar",
          "size": 391892,
          "sha512": "137a2d68e6e39cf72ae393634da1f828cbb7aa5ce14da6f6ebafd31e35c904d03eb0b2b60a29045691aa7e362a6263b9e4814f001012d80ac5c49f30ed2da8a6",
          "sha256": "c695e4934736a73a483255986b4814e1de2950cb596aaf646304907e0fe77430",
          "sha1": "e7def8477862c5f8f866e792b3ed591629fa657e",
          "md5": "7f729fdb3e64f48896c81a9126640230"
        }
      ]
    }
  ]
}
