{
  "formatVersion": "1.1",
  "component": {
    "group": "com.azeoo.sdk",
    "module": "flutter_profile",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "com.llfbandit.app_links",
          "module": "app_links_profile",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_profile",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "dev.steenbakker.mobile_scanner",
          "module": "mobile_scanner_profile",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_profile",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_android_profile",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-3.0.0.aar",
          "url": "flutter_profile-3.0.0.aar",
          "size": 23926608,
          "sha512": "7a91c996d8fedc0a57a382d49dca2b3b8ff12c3108572f5824b7df81a06d68deaba953059b20d763908ca9bddecd96b76e4772c03aad0ac688c6cb0929186465",
          "sha256": "7771db8885cebf1202adad25d7ab066a7be6cf945d563cf466920630c27fe1be",
          "sha1": "4efd3f1c1446d372760d223f0b858c0ab1743143",
          "md5": "6658bad2a83aaafd993529eaf252ec67"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "com.llfbandit.app_links",
          "module": "app_links_profile",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_profile",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "dev.steenbakker.mobile_scanner",
          "module": "mobile_scanner_profile",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_profile",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_profile",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_profile",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_android_profile",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_profile",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-3.0.0.aar",
          "url": "flutter_profile-3.0.0.aar",
          "size": 23926608,
          "sha512": "7a91c996d8fedc0a57a382d49dca2b3b8ff12c3108572f5824b7df81a06d68deaba953059b20d763908ca9bddecd96b76e4772c03aad0ac688c6cb0929186465",
          "sha256": "7771db8885cebf1202adad25d7ab066a7be6cf945d563cf466920630c27fe1be",
          "sha1": "4efd3f1c1446d372760d223f0b858c0ab1743143",
          "md5": "6658bad2a83aaafd993529eaf252ec67"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-3.0.0-sources.jar",
          "url": "flutter_profile-3.0.0-sources.jar",
          "size": 1343,
          "sha512": "fe94d122267682db4447d94c670c2cc9c61a672e03e30915efc30061e335878fd45bbb4031044af35cb46e761b5c57d299ea6c7623d3b5034d2bcc6494467f45",
          "sha256": "61dca2b80ea0428f892f732e3dd00867c456fc7ea68f675c7f5b0e27110c5738",
          "sha1": "3f755eb9ac0fd5c05e65482f225bedcf2c77238e",
          "md5": "4b0ea857810a70ed08257b3d103f9a28"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-3.0.0-javadoc.jar",
          "url": "flutter_profile-3.0.0-javadoc.jar",
          "size": 261620,
          "sha512": "75d21521cba0a69c2f3cecfdc022a99135ca03be1d01e55321a13d9abb2c888bf0c6b81fff272d6987dcc9962a5de03c9561997bf1e10e262265274561ae3158",
          "sha256": "f1e4d7fcd03b61573f4390a7af5baf23797a0c5b7baaf1f3d6c00d0d58b7a944",
          "sha1": "4d970cb6a655f4274c1eae20e31d4dd285ccf1e0",
          "md5": "ca06a2e9f22faec474e82ac1c3d98f08"
        }
      ]
    }
  ]
}
