{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_debug",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_debug-3.0.0.aar",
          "url": "path_provider_android_debug-3.0.0.aar",
          "size": 10809,
          "sha512": "1e43aadf8743080c912faea886fb53cfa3c6e095abc22d2cb98c9843cd10b042d2b2f3cf58e9a1beffe7bf4ebe00cdf0a51e13316e52e6a26120f257f1c3c397",
          "sha256": "bf82481c1e104a28682bd741ec528f4c07123eea5cba006465ddfcbbff6101f0",
          "sha1": "13a589e605bbe8ecb479eb6dd2e5c7c5ecd542e9",
          "md5": "d26bceaf772a1a4315d809b6aeece819"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_debug-3.0.0.aar",
          "url": "path_provider_android_debug-3.0.0.aar",
          "size": 10809,
          "sha512": "1e43aadf8743080c912faea886fb53cfa3c6e095abc22d2cb98c9843cd10b042d2b2f3cf58e9a1beffe7bf4ebe00cdf0a51e13316e52e6a26120f257f1c3c397",
          "sha256": "bf82481c1e104a28682bd741ec528f4c07123eea5cba006465ddfcbbff6101f0",
          "sha1": "13a589e605bbe8ecb479eb6dd2e5c7c5ecd542e9",
          "md5": "d26bceaf772a1a4315d809b6aeece819"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_debug-3.0.0-sources.jar",
          "url": "path_provider_android_debug-3.0.0-sources.jar",
          "size": 4153,
          "sha512": "8d0620e879a6668a7dcb1b54091eac971c86c0f1013d78c2728018c501598d095e00f47e47c7742978594c39df41cb896eb9d9a91c73453f6ebec7f3e3b409c2",
          "sha256": "526f898c1240196664c940f06843d55dd7f6717365c167c476386277cca3d15c",
          "sha1": "9bc69e92e2ab37ebea4cb511e4072550fe34d36a",
          "md5": "b5f0db6ff8f305f4a799b8b39e4da48d"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_debug-3.0.0-javadoc.jar",
          "url": "path_provider_android_debug-3.0.0-javadoc.jar",
          "size": 294225,
          "sha512": "0644f287932d97210b130a1e72168069a60c836cd5eb3e4493fa81fd4b0958782e6b8a16b238a26a617f952b2b0d015e626165a9d423ef2fa28cbcf1f543b6fc",
          "sha256": "424547123733f7b19139ab37d8691efe2550de17020292492d1644db175360d8",
          "sha1": "ea671a19a38f39e13b67b7147030c5f2ef57299d",
          "md5": "df970d6cca62a75ff6fc166829b31fde"
        }
      ]
    }
  ]
}
