{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_profile",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_profile-1.0.0.aar",
          "url": "permission_handler_android_profile-1.0.0.aar",
          "size": 27815,
          "sha512": "8173ea39585c5c716abca1ff53f065678a258218e906a20134a54d49fe3c299d4bffbd0b9a71c1a6eaf0d4ec2424937cd9ad2cd75942d59453aea84dfe857ece",
          "sha256": "b9ee27785e302a594f3bd4172ad2b306e3b63b11e359b5a9cfa5cf577f663ff0",
          "sha1": "16346e9bbf3ef8cbbd686038b70c2611858aa962",
          "md5": "eae26fd20762f7102c8cc640d91c3be6"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_profile-1.0.0.aar",
          "url": "permission_handler_android_profile-1.0.0.aar",
          "size": 27815,
          "sha512": "8173ea39585c5c716abca1ff53f065678a258218e906a20134a54d49fe3c299d4bffbd0b9a71c1a6eaf0d4ec2424937cd9ad2cd75942d59453aea84dfe857ece",
          "sha256": "b9ee27785e302a594f3bd4172ad2b306e3b63b11e359b5a9cfa5cf577f663ff0",
          "sha1": "16346e9bbf3ef8cbbd686038b70c2611858aa962",
          "md5": "eae26fd20762f7102c8cc640d91c3be6"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_profile-1.0.0-sources.jar",
          "url": "permission_handler_android_profile-1.0.0-sources.jar",
          "size": 18177,
          "sha512": "673bc0d22579ac8c7f7a50b04d3f47d4cdb85dbc8aa15bfcb371b64223d3ee8f535385b2e67dfa1230c825ecddb11e45e1a0b74410e608691074c11623d4f06e",
          "sha256": "3301b75b44b9f004580d559b28ab51dd9205289cc88ccc668ce8179f5bf24c67",
          "sha1": "7a9e4cb073bdd84100ad45b7d2c21b036815543f",
          "md5": "6347cb73f0ecc4fc5e825d6de82fca4e"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "permission_handler_android_profile-1.0.0-javadoc.jar",
          "url": "permission_handler_android_profile-1.0.0-javadoc.jar",
          "size": 264575,
          "sha512": "4944b0aae2aea54c36ace334f36d3e6a5527965c439ee5c72976c72b7e112bca32326ecb3324182274877f383106952b34ff3d60857a1cce367e2c2ee18b0da1",
          "sha256": "3daad216a873d4e40654fc65bfa33cbe7a73a479631def98c3843136dc6dec86",
          "sha1": "85f2df461ff8e54cc4c2bb1af1673d4f4f1d1fce",
          "md5": "debd960ffbaeba504cc43776309f7cc0"
        }
      ]
    }
  ]
}
