{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_debug",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-3.0.0.aar",
          "url": "url_launcher_android_debug-3.0.0.aar",
          "size": 23567,
          "sha512": "84140224076215cd064e2780d2a298b6758569bc08b256d2872f8729534efe56d9ef0486a120883a5108fe58d2c50db655bd8c64a7c8e8196f2c9fe5d01bace3",
          "sha256": "27669bab683aa6f2d2143e6b59169c52fb67505f10a8df97b05254aec7328930",
          "sha1": "d429e6aeb66595169327710440a759418142114e",
          "md5": "95ff92bd26891308e0fa3ef2c192647b"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-a8bfdfc394deaed5c57bd45a64ac4294dc976a72"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-3.0.0.aar",
          "url": "url_launcher_android_debug-3.0.0.aar",
          "size": 23567,
          "sha512": "84140224076215cd064e2780d2a298b6758569bc08b256d2872f8729534efe56d9ef0486a120883a5108fe58d2c50db655bd8c64a7c8e8196f2c9fe5d01bace3",
          "sha256": "27669bab683aa6f2d2143e6b59169c52fb67505f10a8df97b05254aec7328930",
          "sha1": "d429e6aeb66595169327710440a759418142114e",
          "md5": "95ff92bd26891308e0fa3ef2c192647b"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_debug-3.0.0-sources.jar",
          "url": "url_launcher_android_debug-3.0.0-sources.jar",
          "size": 9311,
          "sha512": "54980f5c43308ccdbb6cd27d7c0be394e2fe4acdb2135676d56fe2d21349ea8857adbdc269a9c42da2ccbe4bb352364118f88098877b7f87035c898cbab1287d",
          "sha256": "e540ccbfc24b3dfc857f699d206eb036f374b93ae8f2fa470fac2b230dd2e456",
          "sha1": "3d042e070f38e16a3e5839884a275d307903ed42",
          "md5": "4acb37364d6b4535335bfea67e7fff61"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_debug-3.0.0-javadoc.jar",
          "url": "url_launcher_android_debug-3.0.0-javadoc.jar",
          "size": 332767,
          "sha512": "f65e0d9f298d1d7292942884754356a69cdda15c677a53213d90d41378acddb19a1bc2709ed370287418bac9aaf295484d816e90dcbab09f0d89dc15b040e242",
          "sha256": "0060b65474a433010f33545194e6e211683e30ef24db9e95178c4440331b933d",
          "sha1": "19afafbda53fba35345057c80438cb6c8c98dfc9",
          "md5": "08e3877ba7ad2faaa6190819017ae68f"
        }
      ]
    }
  ]
}
