{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.urllauncher",
    "module": "url_launcher_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1e9a811bf8e70466596bcf0ea3a8b5adb5f17f7f"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-1.0.aar",
          "url": "url_launcher_android_debug-1.0.aar",
          "size": 23567,
          "sha512": "84140224076215cd064e2780d2a298b6758569bc08b256d2872f8729534efe56d9ef0486a120883a5108fe58d2c50db655bd8c64a7c8e8196f2c9fe5d01bace3",
          "sha256": "27669bab683aa6f2d2143e6b59169c52fb67505f10a8df97b05254aec7328930",
          "sha1": "d429e6aeb66595169327710440a759418142114e",
          "md5": "95ff92bd26891308e0fa3ef2c192647b"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-1e9a811bf8e70466596bcf0ea3a8b5adb5f17f7f"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "url_launcher_android_debug-1.0.aar",
          "url": "url_launcher_android_debug-1.0.aar",
          "size": 23567,
          "sha512": "84140224076215cd064e2780d2a298b6758569bc08b256d2872f8729534efe56d9ef0486a120883a5108fe58d2c50db655bd8c64a7c8e8196f2c9fe5d01bace3",
          "sha256": "27669bab683aa6f2d2143e6b59169c52fb67505f10a8df97b05254aec7328930",
          "sha1": "d429e6aeb66595169327710440a759418142114e",
          "md5": "95ff92bd26891308e0fa3ef2c192647b"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_debug-1.0-sources.jar",
          "url": "url_launcher_android_debug-1.0-sources.jar",
          "size": 9311,
          "sha512": "54980f5c43308ccdbb6cd27d7c0be394e2fe4acdb2135676d56fe2d21349ea8857adbdc269a9c42da2ccbe4bb352364118f88098877b7f87035c898cbab1287d",
          "sha256": "e540ccbfc24b3dfc857f699d206eb036f374b93ae8f2fa470fac2b230dd2e456",
          "sha1": "3d042e070f38e16a3e5839884a275d307903ed42",
          "md5": "4acb37364d6b4535335bfea67e7fff61"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "url_launcher_android_debug-1.0-javadoc.jar",
          "url": "url_launcher_android_debug-1.0-javadoc.jar",
          "size": 332748,
          "sha512": "433a0db11571b186b8ed1346bc686a2df8c9d197bed3a00cc32359b577ff6d2816a60062b05ff423e516e033e14296547875294d3f62e1535353815de80a28e2",
          "sha256": "27fa586a9f0e7753c73b9b2e340730656cee67d80e3a0cece9bcd23bdfc86645",
          "sha1": "c2394ebaa21bcdd3890cb18cf1b5bd7e029b5fd8",
          "md5": "40a3eafde9c17fb8b265c0f06d1540f1"
        }
      ]
    }
  ]
}
