{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_release",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-1.0.0.aar",
          "url": "path_provider_android_release-1.0.0.aar",
          "size": 10380,
          "sha512": "7b343cb7aa3b9fa94edd9a221527c1a70f7b84ddff55ea1b0c9cdd1acf1497452e0067cfd1202ecf1570137cf07dfc1119594da111f6be112ab97be6ad890f98",
          "sha256": "38d226d89f5abc851752c2b6705c3a900c23d6eb248aeb5887109e56cd555b9c",
          "sha1": "d9aac4d528e692966f42c3b90e9c987f660d0ee3",
          "md5": "13a3ee61af1830d6117d21ad1838a3dd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_release-1.0.0.aar",
          "url": "path_provider_android_release-1.0.0.aar",
          "size": 10380,
          "sha512": "7b343cb7aa3b9fa94edd9a221527c1a70f7b84ddff55ea1b0c9cdd1acf1497452e0067cfd1202ecf1570137cf07dfc1119594da111f6be112ab97be6ad890f98",
          "sha256": "38d226d89f5abc851752c2b6705c3a900c23d6eb248aeb5887109e56cd555b9c",
          "sha1": "d9aac4d528e692966f42c3b90e9c987f660d0ee3",
          "md5": "13a3ee61af1830d6117d21ad1838a3dd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_release-1.0.0-sources.jar",
          "url": "path_provider_android_release-1.0.0-sources.jar",
          "size": 4153,
          "sha512": "8d0620e879a6668a7dcb1b54091eac971c86c0f1013d78c2728018c501598d095e00f47e47c7742978594c39df41cb896eb9d9a91c73453f6ebec7f3e3b409c2",
          "sha256": "526f898c1240196664c940f06843d55dd7f6717365c167c476386277cca3d15c",
          "sha1": "9bc69e92e2ab37ebea4cb511e4072550fe34d36a",
          "md5": "b5f0db6ff8f305f4a799b8b39e4da48d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_release-1.0.0-javadoc.jar",
          "url": "path_provider_android_release-1.0.0-javadoc.jar",
          "size": 294232,
          "sha512": "2e26ef59c94c09c4419561282e98a086cce3e8198d406c095382e817723622dff6c73a43e4a4522029d1a35474af09be3e0dd6f10787e892e9876fa408da5b06",
          "sha256": "426e8118ff74ff21d761ee88fbe0e812f6d912e639ab92c2bb45ad92250ec3bd",
          "sha1": "6812d19c3b4cd7180ac10d71ee2184d3957e83cd",
          "md5": "132dca16f217c8383f8cff1c8aa3eba6"
        }
      ]
    }
  ]
}
