{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.steenbakker.mobile_scanner",
    "module": "mobile_scanner_debug",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile_scanner_debug-1.0.0.aar",
          "url": "mobile_scanner_debug-1.0.0.aar",
          "size": 82697,
          "sha512": "a46eebadb5f07143dad67983ad158c4074f05630f11bbbd64524266babffc03318b5454445fd8f74c84f39bef00668759cf0738d9dba66445da9c3a1295b99b0",
          "sha256": "d4321d3b82e1a9782ead20c5f63747124d1a7e1b9112bf6d4a306c7aedfaa8ef",
          "sha1": "e1e22310edd0feca6a52ea8f9c22c7322c667a6e",
          "md5": "8ee701823d334762c8dd49c20e37fdcd"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c29809135135e262a912cf583b2c90deb9ded610"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mobile_scanner_debug-1.0.0.aar",
          "url": "mobile_scanner_debug-1.0.0.aar",
          "size": 82697,
          "sha512": "a46eebadb5f07143dad67983ad158c4074f05630f11bbbd64524266babffc03318b5454445fd8f74c84f39bef00668759cf0738d9dba66445da9c3a1295b99b0",
          "sha256": "d4321d3b82e1a9782ead20c5f63747124d1a7e1b9112bf6d4a306c7aedfaa8ef",
          "sha1": "e1e22310edd0feca6a52ea8f9c22c7322c667a6e",
          "md5": "8ee701823d334762c8dd49c20e37fdcd"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mobile_scanner_debug-1.0.0-sources.jar",
          "url": "mobile_scanner_debug-1.0.0-sources.jar",
          "size": 24074,
          "sha512": "25c4ad54cfcccb2183fc365ea3330ecf708b36691061841bf62e2914be4ef9e5d5c5f5827a57c6052949ba72e8e2e5e3132406a2673dd40e28b8901c35688f6c",
          "sha256": "d5fea13d7766c2452e9bbb9425d90930732a0a55df10fa949bde4e53b1e017ee",
          "sha1": "242d0d02ffb841abc2db142e5ab97f7a209debcd",
          "md5": "bb0bb4f980749cbce4a05f5a42cab434"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mobile_scanner_debug-1.0.0-javadoc.jar",
          "url": "mobile_scanner_debug-1.0.0-javadoc.jar",
          "size": 391943,
          "sha512": "7ee62d3b61b13fddd996a615d0e88e70eb2ad99afdb00b7908d657bc55c33f3f5a1b2673a7dd1c4b5e14547ad33855ff8aaec5606b5c5ca6d97ce2d92abf8fb1",
          "sha256": "a5c9d6f4dc9034f4474a7e73728b5e196f2041e81295bf7e1c912570a82fd31f",
          "sha1": "13af21c037625d489bcc99a72740ca373630bf54",
          "md5": "511205f61f850d7ea9fef49fe6df4e1c"
        }
      ]
    }
  ]
}
